### ISSUE TITLE
The requrements of the envirnments

### ISSUE THREAD

**Issue by DrJZhou** [ucinlp/facade#1]
Could you please share the versions of allennlp, allennlp-models and so on? I meet some errors when running the codes. Thanks!~

**Comment by jens321** [comment]
Hi @12190143 , thanks for your interest! The version for allennlp-models is hosted here https://github.com/jens321/allennlp-models.git and you can install it with `pip install git+https://github.com/jens321/allennlp-models.git`. For allennlp, it is hosted here https://github.com/Eric-Wallace/allennlp/tree/facade and you can install it using 
```
git clone git@github.com:Eric-Wallace/allennlp.git
cd allennlp
git checkout facade
pip install .
```
Note that these are modified versions of allennlp and allennlp-models so they don't have official release versions associated with them. Let me know if you still have errors after running these! (Feel free to post them here)
